// <auto-generated />
namespace MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmembershiptbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmembershiptbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201704291835283_addmembershiptbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
